### ISSUE TITLE
update to org.gnome.Platform/x86_64/40

### ISSUE THREAD

**Issue by codingepaduli** [flathub/net.christianbeier.Gromit-MPX#1]
Please, 

can you update the runtime to org.gnome.Platform/x86_64/40

Thanks

**Comment by codingepaduli** [comment]
Trying to update the flatpak ecosystem, I got this message:
`
Info: org.gnome.Platform//3.38 is end-of-life, with reason:
   The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   net.christianbeier.Gromit-MPX
`

**Comment by bk138** [comment]
Hi @codingepaduli sry for the late reply, I'm very busy with $$$ work currently but would be happy to review and merge a pull request!
