### ISSUE TITLE
Flathub description contains markdown formatting issue.

### ISSUE THREAD

**Issue by abuhuraira0099** [flathub/net.christianbeier.Gromit-MPX#3]
Markdown tags show up in the screen instead of being applied in Flathub's app description page. 

![Screenshot_٢٠٢٣٠٢١١_١٩٣٩٠٢_Mull](https://user-images.githubusercontent.com/79898595/218261144-b6ce3856-727f-4436-bf17-3e4f35d89fcf.jpg)
Screenshot taken from Flathub Beta website.

**Comment by bbhtt** [comment]
Issue with the Flathub web frontend (both old and new) https://github.com/flathub/website/issues/131

(em tags are supported by appstream spec)

**Comment by bk138** [comment]
Well it actually _used_ to work, I can remember those tags not ending up in the rendering. What do you propose @bbhtt @abuhuraira0099 ?

**Comment by bk138** [comment]
Will be in next release.
