### ISSUE TITLE
Using CLI command "--line" fail

### ISSUE THREAD

**Issue by Taulim** [flathub/net.christianbeier.Gromit-MPX#6]
I'm trying to use the cli command --line and it always respond with:

```
$ flatpak run net.christianbeier.Gromit-MPX -l 200 200 400 400 '#C4A7E7' 6
Unknown Option to control a running Gromit-MPX process: "-l"
Please see the Gromit-MPX manpage for the correct usage

$ flatpak run net.christianbeier.Gromit-MPX --line 200 200 400 400 '#C4A7E7' 6
Unknown Option to control a running Gromit-MPX process: "--line"
Please see the Gromit-MPX manpage for the correct usage
```

Other arguments (e.g. `--clear` and `--toggle`) are working.
Does the flatpak version have this argument disabled?

**Comment by bbhtt** [comment]
It was added last week https://github.com/bk138/gromit-mpx/commit/d30f9b83e681e72ce1ee54de3ac81088fb0bdf9b while Gromit had its last release in September 2022. You have to wait until it lands in a release and then the flatpak can be updated.

**Comment by Taulim** [comment]
Yes, I just realised that look at the code.
Thank you for the quick response!

I understand that there are not many commits on the project.
Since the last release was one year ago do you think a new version is coming soon?
Or could we have a flatpak-beta that walk together with master until it is ready to be final?

**Comment by bk138** [comment]
Upstream is at https://github.com/bk138/gromit-mpx, please see https://github.com/bk138/gromit-mpx/milestone/5 for the next release.
